version: 0.1

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install nodejs
      - npm cache clean -f
      - npm install -g n
  pre_build:
    commands:
      - echo pre_build phase...
      - npm install -g @angular/cli
      - ng --version
  build:
    commands:
      - echo Build started on `date`
      - ng build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/angular-app