version: 0.1

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install nodejs
      - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update && apt-get install yarn
  pre_build:
    commands:
      - echo pre_build phase...
      - npm install @angular/cli
      - npm link @angular/cli
      - npm uninstall @angular-devkit/build-angular
      - npm install --save-dev @angular-devkit/build-angular
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/your-app-name