version: 0.1

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - npm i -g @angular/cli
      - npm install
      - sed 's,https://conduit.productionready.io/api,$URI,g' src/environments/environment.prod.ts
  build:
    commands:
      - ng build --prod --configuration production
      - echo $CODEBUILD_BASE_DIR
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'dist/'